spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:${POSTGRES_LOCAL_PORT}/order_data
    url: jdbc:${POSTGRES_CONNECTION_STRING}
    # username: ${POSTGRES_USER}
    # password: ${POSTGRES_PASSWORD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: ${RABBITMQ_AMQP_LOCAL_PORT}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

server:
  port: ${APP_ORDER_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
