spring:
  # datasource:
  #   driver-class-name: org.postgresql.Driver
  #   url: jdbc:${PG_CONNECTION_STRING}/user_data
  #   username: ${PG_USER}
  #   password: ${PG_PASSWORD}
  # jpa:
  #   database: postgresql
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       format_sql: true
  data:
    mongodb:
      uri: ${MONGO_CONNECTION_STRING}
      database: ${MONGO_DATABASE}
  rabbitmq:
    host: localhost
    port: ${RABBITMQ_AMQP_LOCAL_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

server:
  port: ${APP_MICROSERVICE_USER_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    shutdown:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: management/logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

app:
  message: "This is a message from User Service of eCommerce Microservices Application."
